In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import  RandomForestClassifier
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import  load_digits
digits =load_digits()

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [ ]:
lr= LogisticRegression()
lr.fit(X_train,Y_train)  
lr.score(X_test,Y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


0.9592592592592593

In [ ]:
svm=SVC()
svm.fit(X_train,Y_train)
svm.score(X_test,Y_test)

0.9833333333333333

In [ ]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(X_train,Y_train)
rf.score(X_test,Y_test)

0.9611111111111111

In [ ]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [ ]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [ ]:
 from sklearn.model_selection import StratifiedKFold
 folds=StratifiedKFold(n_splits=3)